---
title: Fundraising Field Guide
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    permalink: /:collection/:title/
  uploads:
    title: Uploads
    output: true
name: Fundraising Field Guide
description: A startup founder's handbook.
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
disqus:
google_analytics:
url: https://matthewcobb.github.io/
baseurl: "/ffg"
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
